PPZ/PPZ/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PPZ.Data;
using PPZ.Models;

namespace PPZ.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public MessagesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = await _userManager.GetUserIdAsync(await _userManager.GetUserAsync(User));

            List<MessagesModel> messages = new List<MessagesModel>();

            var people = await _context.Messages
                .Join(_context.ApplicationUsers, m => m.SenderUserId, au => au.Id, (m, au) => new { m, au })
                .Where(mau => mau.m.ReceiverUserId == userId)
                .Select(mau => mau.au)
                .ToListAsync();

            people.AddRange(await _context.Messages
                .Join(_context.ApplicationUsers, m => m.ReceiverUserId, au => au.Id, (m, au) => new { m, au })
                .Where(mau => mau.m.SenderUserId == userId)
                .Select(mau => mau.au)
                .ToListAsync());

            foreach (var person in people.Distinct())
            {
                string name = "";
                if (person.StudentId != null)
                {
                    name = await _context.Students
                        .Where(s => s.StudentId == person.StudentId)
                        .Select(s => s.FullName)
                        .SingleOrDefaultAsync();
                }
                if (person.GuardianId != null)
                {
                    name = await _context.Guardians
                        .Where(s => s.GuardianId == person.GuardianId)
                        .Select(s => s.FullName)
                        .SingleOrDefaultAsync();
                }
                if (person.TeacherId != null)
                {
                    name = await _context.Teachers
                        .Where(s => s.TeacherId == person.TeacherId)
                        .Select(s => s.FullName)
                        .SingleOrDefaultAsync();
                }

                var messageFrom = await _context.Messages
                    .Where(m => m.ReceiverUserId == userId)
                    .Where(m => m.SenderUserId == person.Id)
                    .OrderByDescending(m => m.Time)
                    .FirstOrDefaultAsync();

                var messageTo = await _context.Messages
                    .Where(m => m.SenderUserId == userId)
                    .Where(m => m.ReceiverUserId == person.Id)
                    .OrderByDescending(m => m.Time)
                    .FirstOrDefaultAsync();

                messages.Add(new MessagesModel
                {
                    UserId = person.Id,
                    UserName = name,
                    Time = messageTo.Time,
                    ShortContent = messageTo.Content + "..."
                });

                /*if (messageFrom.Time > messageTo.Time)
                {
                    
                }
                else
                {
                    messages.Add(new MessagesModel
                    {
                        UserId = person.Id,
                        UserName = name,
                        Time = messageTo.Time,
                        ShortContent = messageTo.Content.Substring(0, 30) + "..."
                    });
                }*/
            }

            return View(messages);
        }

        public async Task<IActionResult> NewMessage()
        {
            AdminInfo adminInfo = null;
            List<GroupInfo> contacts = new List<GroupInfo>();

            if (User.IsInRole("Admin"))
            {
                var groups = await _context.Groups.ToListAsync();

                foreach (var group in groups)
                {
                    var teachers = await _context.Teachers
                        .Join(_context.GroupTeachers, t => t.TeacherId, gt => gt.TeacherId, (t, gt) => new { t, gt })
                        .Where(tgt => tgt.gt.GroupId == group.GroupId)
                        .Select(tgt => tgt.t)
                        .ToListAsync();

                    List<TeacherInfo> teacherInfos = new List<TeacherInfo>();

                    foreach (var teacher in teachers)
                    {
                        var teacherAccountId = await _context.ApplicationUsers
                            .Where(au => au.TeacherId == teacher.TeacherId)
                            .Select(au => au.Id)
                            .SingleOrDefaultAsync();

                        teacherInfos.Add(new TeacherInfo
                        {
                            Teacher = teacher,
                            AccountId = teacherAccountId,
                            Send = false
                        });
                    }

                    var students = await _context.Students
                        .Join(_context.GroupStudents, s => s.StudentId, gs => gs.StudentId, (s, gs) => new { s, gs })
                        .Where(sgs => sgs.gs.GroupId == group.GroupId)
                        .Select(sgs => sgs.s)
                        .ToListAsync();

                    List<StudentGuardianInfo> studentsAndGuardians = new List<StudentGuardianInfo>();

                    foreach (var student in students)
                    {
                        var studentAccountId = await _context.ApplicationUsers
                            .Where(au => au.StudentId == student.StudentId)
                            .Select(au => au.Id)
                            .SingleOrDefaultAsync();

                        var guardian = await _context.Guardians
                            .Join(_context.StudentGuardians, g => g.GuardianId, sg => sg.GuardianId, (g, sg) => new { g, sg })
                            .Where(gsg => gsg.sg.StudentId == student.StudentId)
                            .Select(gsg => gsg.g)
                            .FirstOrDefaultAsync();

                        string guardianAccountId = "";
                        if (guardian != null)
                        {
                            guardianAccountId = await _context.ApplicationUsers
                                .Where(au => au.GuardianId == guardian.GuardianId)
                                .Select(au => au.Id)
                                .SingleOrDefaultAsync();
                        }

                        studentsAndGuardians.Add(new StudentGuardianInfo
                        {
                            Student = student,
                            StudentAccountId = studentAccountId,
                            StudentSend = false,
                            Guardian = guardian,
                            GuardianAccountId = guardianAccountId,
                            GuardianSend = false
                        });
                    }

                    var groupInfo = new GroupInfo
                    {
                        Group = group,
                        Teachers = teacherInfos,
                        StudentsAndGuardians = studentsAndGuardians
                    };

                    contacts.Add(groupInfo);
                }
            }

            return View(new NewMessageModel
            {
                Admin = adminInfo,
                Contacts = contacts
            });
        }

        [HttpPost]
        public async Task<IActionResult> NewMessage(NewMessageModel model)
        {
            var userId = await _userManager.GetUserIdAsync(await _userManager.GetUserAsync(User));

            if (model.Admin != null)
            {
                _context.Messages.Add(new Message
                {
                    ReceiverUserId = model.Admin.AccountId,
                    SenderUserId = userId,
                    Content = model.Message,
                    IsDeletedByReceiver = false,
                    IsDeletedBySender = false,
                    IsViewed = false,
                    Time = DateTime.Now
                });
            }

            List<string> teachers = new List<string>();

            foreach (var item in model.Contacts)
            {
                var groupTeachers = item.Teachers
                    .Where(t => t.Send == true)
                    .Select(t => t.AccountId)
                    .ToList();
                teachers.AddRange(groupTeachers);
            }

            foreach (var teacher in teachers.Distinct())
            {
                _context.Messages.Add(new Message
                {
                    ReceiverUserId = teacher,
                    SenderUserId = userId,
                    Content = model.Message,
                    IsDeletedByReceiver = false,
                    IsDeletedBySender = false,
                    IsViewed = false,
                    Time = DateTime.Now
                });
            }

            List<string> students = new List<string>();

            foreach (var item in model.Contacts)
            {
                var groupStudents = item.StudentsAndGuardians
                    .Where(s => s.StudentSend == true)
                    .Select(s => s.StudentAccountId)
                    .ToList();
                students.AddRange(groupStudents);
            }

            foreach (var student in students.Distinct())
            {
                _context.Messages.Add(new Message
                {
                    ReceiverUserId = student,
                    SenderUserId = userId,
                    Content = model.Message,
                    IsDeletedByReceiver = false,

PPZ/PPZ/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PPZ.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{string themePath; }
@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    themePath = (user.ThemePath ?? "~/lib/bootstrap/dist/css/superhero-bootstrap.css");
}
else
{
    themePath = "~/lib/bootstrap/dist/css/superhero-bootstrap.css";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyAM</title>
    <link rel="stylesheet" href="@themePath" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/responsive-nao-calendar/aicon/style.css">
    <link rel="stylesheet" href="~/lib/responsive-nao-calendar/css/jquery-nao-calendar.css">

    @RenderSection("stylesheets", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo-white.png" height="40" asp-append-version="true"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <partial name="_NavigationPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <br />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2020 - MyAM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

PPZ/PPZ/Views/Shared/_NavigationPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using PPZ.Data
@inject SignInManager<ApplicationUser> SignInManager

    <ul class="navbar-nav flex-grow-1">
        @if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link font-weight-bold dropdown-toggle" href="#" id="adminToolsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin Tools
                    </a>
                    <div class="dropdown-menu" aria-labelledby="adminToolsDropdown">
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="Accounts" asp-action="Index">Accounts</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="RFIDMap" asp-action="Index">RFID IDs</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link font-weight-bold dropdown-toggle" href="#" id="managerDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Manager
                    </a>
                    <div class="dropdown-menu" aria-labelledby="managerDropdown">
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="Students" asp-action="Index">Students</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="Guardians" asp-action="Index">Guardians</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Admin" asp-controller="Groups" asp-action="Index">Groups</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                </li>
            }
            else if (User.IsInRole("Student"))
            {
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Student" asp-controller="Guardians" asp-action="Index">Guardians</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Student" asp-controller="Groups" asp-action="Index">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                </li>
            }
            else if (User.IsInRole("Guardian"))
            {
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Guardian" asp-controller="Students" asp-action="Index">Students</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Guardian" asp-controller="Groups" asp-action="Index">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                </li>
            }
            else if (User.IsInRole("Teacher"))
            {
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Teacher" asp-controller="RFIDMap" asp-action="Index">RFID IDs</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link font-weight-bold dropdown-toggle" href="#" id="managerDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Manager
                    </a>
                    <div class="dropdown-menu" aria-labelledby="managerDropdown">
                        <a class="dropdown-item font-weight-bold" asp-area="Teacher" asp-controller="Students" asp-action="Index">Students</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Teacher" asp-controller="Guardians" asp-action="Index">Guardians</a>
                        <a class="dropdown-item font-weight-bold" asp-area="Teacher" asp-controller="Groups" asp-action="Index">Groups</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" asp-area="Identity" asp-page="/Account/Manage/Index">--- Complete your profile ---</a>
                </li>
            }
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Calendar">Calendar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
        }
    </ul>