PPZ/PPZ/Areas/Student/Models/GroupModel.cs
using PPZ.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PPZ.Areas.Students.Models
{
    public class GroupModel
    {
        public Group Group { get; set; }
        public List<Teacher> GroupTeachers { get; set; }
        public List<Student> GroupStudents { get; set; }
    }
}

PPZ/PPZ/Areas/Student/Models/StudentModel.cs
using PPZ.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PPZ.Areas.Students.Models
{
    public class StudentModel
    {
        public Student Student { get; set; }
        public List<Guardian> Guardians { get; set; }
        public List<Group> Groups { get; set; }
        public string StudentKey { get; set; }
        public string GuardianKey { get; set; }
    }
}

PPZ/PPZ/Areas/Admin/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPZ.Areas.Admin.Models;
using PPZ.Data;

namespace PPZ.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public StudentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Admin/Students
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());                  
        }

        public IActionResult ImportCsv()
        {
            CsvModel csvModel = new CsvModel();
            return View(csvModel);
        }

        [HttpPost]
        public async Task<IActionResult> ImportCsv(CsvModel csvModel)
        {

            string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "csv");
            string fileName = csvModel.FormFile.FileName;
            string filePath = Path.Combine(uploadsFolder,fileName);

            using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
            {
                await csvModel.FormFile.CopyToAsync(fileStream);
            }

            using (var reader = new StreamReader(filePath))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Configuration.RegisterClassMap<StudentCsvMap>();
                var students = csv.GetRecords<Student>();

                try
                {
                    await _context.AddRangeAsync(students);
                    await _context.SaveChangesAsync();
                }
                catch(Exception e)
                {
                    var model = new CsvErrorPageModel() { ErrorMessage = e.Message, FilePath = filePath };
                    return View("../CsvErrorPage", model);
                }
            }

            System.IO.File.Delete(filePath);

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            var guardians = await _context.Guardians
                .Join(_context.StudentGuardians, g => g.GuardianId, sg => sg.GuardianId, (g, sg) => new { g, sg })
                .Where(gsg => gsg.sg.StudentId == id)
                .Select(gsg => gsg.g)
                .ToListAsync();

            var groups = await _context.Groups
                .Join(_context.GroupStudents, g => g.GroupId, gs => gs.GroupId, (g, gs) => new { g, gs })
                .Where(ggs => ggs.gs.StudentId == id)
                .Select(ggs => ggs.g)
                .ToListAsync();

            var studentKey = await _context.AccessKeys
                .Where(k => k.StudentId == id)
                .Where(k => k.Guardian == false)
                .FirstOrDefaultAsync();
            string studentKeyString = "Click below to generate a new key";
            if (studentKey != null)
                studentKeyString = studentKey.Key;

            var guardianKey = await _context.AccessKeys
                .Where(k => k.StudentId == id)
                .Where(k => k.Guardian == true)
                .FirstOrDefaultAsync();
            string guardianKeyString = "Click below to generate a new key";
            if (guardianKey != null)
                guardianKeyString = guardianKey.Key;

            return View(new StudentModel
            { 
                Student = student,
                Guardians = guardians,
                Groups = groups,
                StudentKey = studentKeyString,
                GuardianKey = guardianKeyString
            });
        }

        // GET: Admin/Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentId,FirstName,SecondName,LastName,DateOfBirth,Address,EmailAddress,PhoneNumber,Height,Weight,Info,IsActive")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Admin/Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Admin/Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentId,FirstName,SecondName,LastName,DateOfBirth,Address,EmailAddress,PhoneNumber,Height,Weight,Info,IsActive")] Student student)
        {
            if (id != student.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Admin/Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Admin/Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            var user = await _context.ApplicationUsers.Where(u => u.StudentId == id).SingleOrDefaultAsync();
            if (user != null)
            {
                await _userManager.RemoveFromRoleAsync(user, "Student");
                user.StudentId = null;
                _context.Update(user);
            }
            var studentGuardians = await _context.StudentGuardians.Where(sg => sg.StudentId == id).ToListAsync();
            _context.StudentGuardians.RemoveRange(studentGuardians);
            var groupStudents = await _context.GroupStudents.Where(gs => gs.StudentId == id).ToListAsync();
            _context.GroupStudents.RemoveRange(groupStudents);
            var accessKeys = await _context.AccessKeys.Where(a => a.StudentId == id).ToListAsync();
            _context.AccessKeys.RemoveRange(accessKeys);
            var attendances = await _context.Attendances.Where(a => a.StudentId == id).ToListAsync();
            _context.Attendances.RemoveRange(attendances);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Admin/Students/GenerateKeyForStudent/5        
        public async Task<IActionResult> GenerateKeyForStudent(int id)
        {
            var oldKey = await _context.AccessKeys
                .Where(k => k.Guardian == false)
                .Where(k => k.StudentId == id).SingleOrDefaultAsync();
            if (oldKey != null)
            {
                _context.Remove(oldKey);
            }
            string genKey;
            AccessKey duplicate;
            do
            {
                genKey = GenerateRandomString(8);
                duplicate = await _context.AccessKeys.Where(k => k.Key == genKey).SingleOrDefaultAsync();
            } while (duplicate != null);
            AccessKey accessKey = new AccessKey
            {
                DateCreated = DateTime.Now,
                Key = genKey,
                KeyHash = SharedFunctions.GetSHA256FromString(genKey),
                StudentId = id,

PPZ/PPZ/Areas/Student/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPZ.Areas.Students.Models;
using PPZ.Data;

namespace PPZ.Areas.Students.Controllers
{
    [Area("Student")]
    [Authorize(Roles = "Student")]
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public GroupsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Student/Groups
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var groupStudents = await _context.GroupStudents.Where(gS => gS.StudentId == user.StudentId).Include(gS => gS.Group).ToListAsync();
            var groups = new List<Group>();

            foreach (var groupStudent in groupStudents)
            {
                groups.Add(groupStudent.Group);
            }

            return View(groups);
        }

        // GET: Student/Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers.ToListAsync();

            var groupTeachers = teachers
                .Join(_context.GroupTeachers, t => t.TeacherId, gt => gt.TeacherId, (t, gt) => new { t, gt })
                .Where(tgt => tgt.gt.GroupId == id)
                .Select(tgt => tgt.t)
                .ToList();

            var students = await _context.Students.ToListAsync();

            var groupStudents = students
                .Join(_context.GroupStudents, s => s.StudentId, gs => gs.StudentId, (s, gs) => new { s, gs })
                .Where(sgs => sgs.gs.GroupId == id)
                .Select(sgs => sgs.s)
                .ToList();

            return View(new GroupModel 
            { 
                Group = @group,
                GroupTeachers = groupTeachers,
                GroupStudents = groupStudents
            });
        }

    }
}

PPZ/PPZ/Areas/Student/Controllers/GuardiansController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPZ.Areas.Students.Models;
using PPZ.Data;

namespace PPZ.Areas.Students.Controllers
{
    [Area("Student")]
    [Authorize(Roles = "Student")]
    public class GuardiansController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public GuardiansController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Admin/Guardians
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var studentGuardians = await _context.StudentGuardians.Where(sG => sG.StudentId == user.StudentId).Include(sG => sG.Guardian).ToListAsync();
            var guardians = new List<Guardian>();

            foreach(var studentGuardian in studentGuardians)
            {
                guardians.Add(studentGuardian.Guardian);
            }

            return View(guardians);
        }

  

        // GET: Admin/Guardians/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guardian = await _context.Guardians
                .FirstOrDefaultAsync(m => m.GuardianId == id);
            if (guardian == null)
            {
                return NotFound();
            }

            return View(guardian);
        }


    }
}

PPZ/PPZ/Areas/Student/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPZ.Areas.Students.Models;
using PPZ.Data;

namespace PPZ.Areas.Students.Controllers
{
    [Area("Student")]
    [Authorize(Roles = "Student")]    
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TeachersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Admin/Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.TeacherId == id);

            if (teacher == null)
            {
                return NotFound();
            }

            var groups = await _context.Groups
                .Join(_context.GroupTeachers, g => g.GroupId, gs => gs.GroupId, (g, gs) => new { g, gs })
                .Where(ggs => ggs.gs.TeacherId == id)
                .Select(ggs => ggs.g)
                .ToListAsync();

            return View(new TeacherModel
            {
                Teacher = teacher,
                Groups = groups
            });
        }

    }
}

PPZ/PPZ/Areas/Teacher/Views/Students/Create.cshtml
@model PPZ.Data.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <textarea asp-for="Info" class="form-control"></textarea>
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <select asp-for="IsActive" class="form-control">
                    <option value="True">Active</option>
                    <option value="False">Inactive</option>
                </select>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" /> |
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

PPZ/PPZ/Areas/Teacher/Views/Students/Delete.cshtml
@model PPZ.Data.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        @if (Model.IsActive)
        {
            <dd>Active</dd>
        }
        else
        {
            <dd>Inactive</dd>
        }
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-route-id="@Model.StudentId" class="btn btn-primary">Cancel</a>
    </form>
</div>

PPZ/PPZ/Areas/Teacher/Views/Students/Details.cshtml
@model PPZ.Areas.Teachers.Models.StudentModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student&emsp;<a asp-action="Edit" asp-route-id="@Model.Student.StudentId" class="btn btn-info btn-sm">Edit</a></h4>
    <hr />
    <dl class="row">
        @if (!Model.Student.IsActive)
        {
            <dt class="col-sm-2">
                Inactive student
            </dt>
            <dd class="col-sm-10">
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.SecondName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.SecondName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.EmailAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.EmailAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Height)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.Info)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Info)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.IsActive)
        </dt>
        @if (Model.Student.IsActive)
        {
            <dd class="col-sm-10">Active</dd>
        }
        else
        {
            <dd class="col-sm-10">Inactive</dd>
        }
    </dl>
    <h4>Student's groups</h4>
    <hr />
    <table class="table table-striped table-responsive-lg">
    @foreach (var item in Model.Groups)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-controller="Groups" asp-action="Details" asp-route-id="@item.GroupId" class="btn btn-primary btn-sm">Details</a>
            </td>
        </tr>
    }
    </table>
    <h4>Student's guardians</h4>
    <hr />
    <table class="table table-striped table-responsive-lg">
    @foreach (var item in Model.Guardians)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                <a asp-controller="Guardians" asp-action="Details" asp-route-id="@item.GuardianId" class="btn btn-primary btn-sm">Details</a>
            </td>
        </tr>
    } 
    </table>   
    <h4>Access keys for accounts</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            Key for student account
        </dt>
        <dd class="col-sm-8">
            @Model.StudentKey
        </dd>
        <dt class="col-sm-3">
            Key for guardian account
        </dt>
        <dd class="col-sm-8">
            @Model.GuardianKey
        </dd>
    </dl>
    <form asp-action="GenerateKeyForStudent" asp-route-id="@Model.Student.StudentId" class="d-inline">        
        <input type="submit" class="btn btn-warning" value="Generate key for student" /> |
    </form>      
    <form asp-action="GenerateKeyForGuardian" asp-route-id="@Model.Student.StudentId" class="d-inline">
        <input type="submit" class="btn btn-danger" value="Generate key for guardian" />
    </form>    
    <hr />
</div>
<div>
    <a asp-action="Delete" asp-route-id="@Model.Student.StudentId" class="btn btn-danger">Delete</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

PPZ/PPZ/Areas/Teacher/Views/Students/ImportCsv.cshtml
@model PPZ.Areas.Teachers.Models.CsvModel
@{
    ViewData["Title"] = "Import .csv";
}

<h1>Import</h1>
<h4>Students</h4>
<div class="csv-input">
    <form enctype="multipart/form-data" method="post">
        <div class="form-group">
            <div class="custom-file">
                <input asp-for="FormFile" class="form-control custom-file-input" />
                <span asp-validation-for="FormFile" class="text-danger"></span>
                <label class="custom-file-label">Choose .csv file...</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        let input = document.querySelector(".custom-file-input");
        input.addEventListener("change", function() {
            let filename = input.value.split("\\").pop();
            let label = document.querySelector(".custom-file-label");
            label.innerHTML = filename;
        });
    </script>
}